#!/usr/bin/env python3
"""Demo recorder v2 — the walkthrough a judge actually watches.

Differences from record_demo.py, all of them things Joseph asked for on 2 Sep:

  * A VISIBLE CURSOR. Playwright's real pointer is not captured in the video, so a
    lime bubble is injected into the page and moved in lockstep with page.mouse.
    Every click is preceded by a visible travel and a pulse ring, so a judge can see
    what is being pressed rather than watching the page change by itself.
  * Smooth. The cursor eases via a CSS transition, scrolling is `behavior:'smooth'`,
    and nothing teleports.
  * Quicker. One linear pass, no chapter cards mid-flow.
  * The exact workflow Joseph specified: land on the home page, scroll to the prompt,
    press Draft with Ratify, scroll the obligations showing accept/remove, resolve
    them all, ratify, send for signature, then open the draft PDF and show the
    contract that was produced.

The PDF at the end is the real file the app generated: headless Chromium downloads
rather than renders a PDF, so page 1 is rasterised with pypdfium2 and shown in an
in-page viewer captioned with the real /doc/ URL.
"""
from __future__ import annotations

import argparse, base64, io, os, shutil, socket, subprocess, sys, time, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent.parent
VIDEO_DIR = ROOT / "build" / "video2"
MP4 = VIDEO_DIR / "ratify-demo.mp4"
W, H = 1280, 800

PROMPT = ("Draft an engagement letter for Meridian Consulting FZ-LLC - bookkeeping and VAT "
          "filing for the quarter ending 31 December, AED 12,000, paid monthly. "
          "Signer is Layla Haddad, layla@meridian.example")

# --- injected once per document, survives every navigation --------------------------
OVERLAY = r"""
(() => {
  const install = () => {
  if (!document.body || document.getElementById('__cur')) return;
  const css = document.createElement('style');
  css.textContent = `
  #__cur{position:fixed;left:0;top:0;width:26px;height:26px;margin:-13px 0 0 -13px;
    border-radius:50%;background:radial-gradient(circle at 34% 32%,#d6ff8a 0%,#8CFF1A 46%,#63c40c 100%);
    box-shadow:0 0 0 2px rgba(8,14,6,.85),0 0 22px 6px rgba(140,255,26,.45);
    z-index:2147483647;pointer-events:none;opacity:0;
    transition:transform .30s cubic-bezier(.25,.7,.3,1),opacity .25s ease;}
  #__cur.on{opacity:1}
  #__ring{position:fixed;left:0;top:0;width:26px;height:26px;margin:-13px 0 0 -13px;border-radius:50%;
    border:2px solid #8CFF1A;z-index:2147483646;pointer-events:none;opacity:0;}
  @keyframes __pulse{0%{transform:scale(1);opacity:.95}100%{transform:scale(3.4);opacity:0}}
  #__ring.go{animation:__pulse .55s ease-out}
  #__cap{position:fixed;left:0;right:0;bottom:0;z-index:2147483645;pointer-events:none;
    padding:20px 40px 24px;background:linear-gradient(to top,rgba(4,8,3,.96),rgba(4,8,3,0));
    font:500 21px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    color:#e8f2e4;text-align:center;opacity:0;transition:opacity .35s ease;}
  #__cap.on{opacity:1}
  #__cap b{color:#8CFF1A;font-weight:650}
  #__pdf{position:fixed;inset:0;z-index:2147483644;background:rgba(3,6,2,.93);
    display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;
    opacity:0;transition:opacity .45s ease;pointer-events:none;backdrop-filter:blur(3px)}
  #__pdf.on{opacity:1}
  #__pdf .bar{font:600 12px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em;
    color:#8CFF1A;text-transform:uppercase}
  #__pdf img{max-height:82vh;border-radius:6px;box-shadow:0 30px 90px rgba(0,0,0,.8);
    border:1px solid rgba(140,255,26,.25);background:#fff}
  #__pdf .url{font:400 12px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#7d8a80}`;
  document.head.appendChild(css);
  const mk=(id)=>{const d=document.createElement('div');d.id=id;document.body.appendChild(d);return d;};
  const cur=mk('__cur'), ring=mk('__ring'), cap=mk('__cap'), pdf=mk('__pdf');
  window.__move=(x,y)=>{cur.classList.add('on');
    cur.style.transform=`translate(${x}px,${y}px)`;ring.style.transform=`translate(${x}px,${y}px)`;};
  window.__pulse=()=>{ring.classList.remove('go');void ring.offsetWidth;ring.classList.add('go');};
  window.__say=(t)=>{if(!t){cap.classList.remove('on');return;}cap.innerHTML=t;cap.classList.add('on');};
  window.__pdfShow=(src,url)=>{pdf.innerHTML=
    `<div class="bar">Document generated by Ratify</div><img src="${src}"><div class="url">${url}</div>`;
    pdf.classList.add('on');};
  };
  install();
  if (!document.getElementById('__cur')) {
    document.addEventListener('DOMContentLoaded', install, {once:true});
  }
})();
"""


class Stage:
    def __init__(self, page, base):
        self.p, self.base = page, base
        self.x, self.y = W // 2, H - 120

    def hud(self):
        self.p.evaluate(OVERLAY)
        self.p.evaluate("([x,y])=>window.__move(x,y)", [self.x, self.y])

    def say(self, text, hold=0.0):
        self.p.evaluate("t=>window.__say(t)", text)
        if hold:
            time.sleep(hold)

    def move(self, x, y, settle=0.34):
        self.x, self.y = int(x), int(y)
        self.p.evaluate("([x,y])=>window.__move(x,y)", [self.x, self.y])
        self.p.mouse.move(self.x, self.y)
        time.sleep(settle)

    def scroll_to(self, sel=None, top=None, pause=1.0):
        if top is None:
            top = self.p.evaluate(
                "s=>{const e=document.querySelector(s);if(!e)return 0;"
                "return window.scrollY+e.getBoundingClientRect().top-140;}", sel)
        self.p.evaluate("t=>window.scrollTo({top:t,behavior:'smooth'})", top)
        time.sleep(pause)

    def box(self, sel):
        el = self.p.query_selector(sel)
        if not el:
            return None
        b = el.bounding_box()
        if not b or b["y"] < 60 or b["y"] + b["height"] > H - 60:
            el.scroll_into_view_if_needed()
            self.p.evaluate("()=>{const y=window.scrollY;window.scrollTo({top:y,behavior:'smooth'})}")
            time.sleep(0.7)
            b = el.bounding_box()
        return b

    def hover(self, sel, settle=0.45):
        b = self.box(sel)
        if not b:
            return False
        self.move(b["x"] + b["width"] / 2, b["y"] + b["height"] / 2, settle)
        return True

    def click(self, sel, after=0.9, nav=False):
        if not self.hover(sel):
            return False
        self.p.evaluate("()=>window.__pulse()")
        time.sleep(0.26)
        if nav:
            with self.p.expect_navigation(wait_until="load"):
                self.p.click(sel)
            self.hud()
            self.p.evaluate("()=>window.scrollTo({top:0})")
        else:
            self.p.click(sel)
        time.sleep(after)
        return True


def free_port():
    s = socket.socket(); s.bind(("127.0.0.1", 0)); p = s.getsockname()[1]; s.close(); return p


def pdf_png(url):
    import pypdfium2 as pdfium
    raw = urllib.request.urlopen(url, timeout=20).read()
    page = pdfium.PdfDocument(raw)[0]
    img = page.render(scale=2.1).to_pil()
    buf = io.BytesIO(); img.save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def record(fast=False, pace=1.0):
    k = 0.25 if fast else pace
    def s(t): time.sleep(t * k)

    if VIDEO_DIR.exists():
        shutil.rmtree(VIDEO_DIR)
    VIDEO_DIR.mkdir(parents=True)

    port = free_port()
    srv = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", str(port)],
        cwd=str(ROOT), env=dict(os.environ, DRY_RUN="true"),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    base = f"http://127.0.0.1:{port}"
    for _ in range(80):
        try:
            socket.create_connection(("127.0.0.1", port), 0.5).close(); break
        except OSError:
            time.sleep(0.5)
    time.sleep(1.5)

    t0 = time.time()
    try:
        with sync_playwright() as pw:
            br = pw.chromium.launch()
            ctx = br.new_context(viewport={"width": W, "height": H},
                                 record_video_dir=str(VIDEO_DIR),
                                 record_video_size={"width": W, "height": H})
            pg = ctx.new_page()
            pg.add_init_script(OVERLAY)
            pg.goto(base, wait_until="networkidle")
            st = Stage(pg, base)
            st.hud()

            # 1 — the front door
            s(1.0)
            st.say("<b>Ratify</b> — an agent drafts your engagement letter, "
                   "and structurally cannot sign it.", 1.0); s(2.6)

            # 2 — down to the prompt
            st.say("You describe the engagement in plain English.")
            st.scroll_to("#demo", pause=1.4 * k); s(0.6)
            st.hover("#prompt", 0.5); s(2.4)

            # 3 — draft
            st.say("Press <b>Draft with Ratify</b>."); s(0.7)
            st.click("#draft-button", after=1.0, nav=True)
            s(0.9)

            # 4 — the review screen
            st.say("The agent drafted the letter — and stopped.", 0.6); s(2.2)
            st.scroll_to("#terms", top=None, pause=1.2 * k) if pg.query_selector("#terms") else st.scroll_to(top=420, pause=1.2 * k)
            st.say("Every material term is tagged by <b>where it came from</b>. "
                   "The ones the agent invented block the gate."); s(2.8)

            # 5 — accept / remove, shown deliberately on the first term
            first = "article.term:not(.resolved)"
            if pg.query_selector(f"{first} button[value=accept]"):
                st.hover(f"{first} button[value=accept]", 0.5); s(1.5)
            if pg.query_selector(f"{first} button[value=remove]"):
                st.say("Accept it, replace it with your own value, or remove it outright.")
                st.hover(f"{first} button[value=remove]", 0.5); s(1.9)

            # 6 — resolve every blocking term
            st.say("Each one needs a human decision — one at a time.")
            removed = False
            for i in range(14):
                sel_r = f"{first} button[value=remove]"
                sel_a = f"{first} button[value=accept]"
                if not pg.query_selector(sel_a):
                    break
                if not removed and pg.query_selector(sel_r):
                    st.click(sel_r, after=0.5, nav=True); removed = True
                else:
                    st.click(sel_a, after=0.45, nav=True)
                st.scroll_to(first, pause=0.75 * k) if pg.query_selector(first) else None
                if i == 1:
                    st.say("Nothing here is a bulk approve.")

            # 7 — the gate opens
            st.scroll_to(".gate-shell", pause=1.1 * k)
            st.say("All resolved. <b>The signature gate opens.</b>"); s(2.4)

            # 8 — ratify
            st.say("One human authorisation, bound to this exact document.")
            st.click('form[action$="/ratify"] button', after=0.8, nav=True)
            st.scroll_to(".gate-shell", pause=1.0 * k); s(1.6)

            # 9 — send
            st.say("Only now can an envelope be released — from the parent process, "
                   "never the agent."); s(1.4)
            st.click('form[action$="/send"] button', after=0.9, nav=True)
            st.scroll_to(".gate-shell", pause=1.0 * k)
            st.say("Sent for signature."); s(2.2)

            # 10 — the document itself
            href = pg.get_attribute('a[href^="/doc/"]', "href")
            png = pdf_png(base + href)
            pg.evaluate("s=>{const a=document.querySelector('a[href^=\"/doc/\"]');"
                        "a.removeAttribute('target');"
                        "a.addEventListener('click',e=>e.preventDefault(),{capture:true});}", None)
            st.scroll_to(top=0, pause=1.0 * k)
            st.say("And this is the contract that was actually produced.")
            st.click('a[href^="/doc/"]', after=0.5)
            pg.evaluate("([src,u])=>window.__pdfShow(src,u)", [png, href])
            s(1.0); st.say("Rendered by the <b>parent</b>, from the term sheet the human ratified — "
                           "not from bytes the agent supplied."); s(4.2)
            st.say("")
            s(1.2)

            ctx.close()
            br.close()
    finally:
        srv.terminate()

    print(f"walkthrough took {time.time()-t0:.0f}s")
    webm = max(VIDEO_DIR.glob("*.webm"), key=lambda p: p.stat().st_size)
    print(f"video: {webm} ({webm.stat().st_size:,} bytes)")
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(webm),
                    "-c:v", "libx264", "-preset", "slow", "-crf", "23",
                    "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(MP4)], check=True)
    print(f"mp4:   {MP4} ({MP4.stat().st_size:,} bytes)")
    return MP4


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--fast", action="store_true", help="quarter-speed timings, for checking it runs")
    ap.add_argument("--pace", type=float, default=1.0, help="multiplier on every dwell")
    a = ap.parse_args()
    record(fast=a.fast, pace=a.pace)
